services:
  - type: web
    name: cinematch-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: OMDB_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: movierecomandation-60b84
